django-calendar1/cal/urls.py
from django.urls import path
from . import views

app_name = 'cal'
urlpatterns = [
    path('index/', views.index, name='index'),
    path('calendar/', views.CalendarView.as_view(), name='calendar'),
    path('event/new/', views.event, name='event_new'),
    path('event/edit/<int:event_id>/', views.event, name='event_edit'),

    path('main/', views.main),
    path('user/', views.user),
    path('index/',views.index),      
    path('calendar/',views.CalendarView.as_view()),
]

django-calendar1/djangocalendar/urls.py
from django.contrib import admin
from django.urls import path, include
from cal import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cal.urls')),
    path('mobile/', include('cal.urls')),
    path('login/', views.login),
    path('home/', views.home),
]

django-calendar1/cal/models.py
from django.db import models
from django.urls import reverse

class Event(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()

    @property
    def get_html_url(self):
        url = reverse('cal:event_edit', args=(self.id,))
        return f'<a href="{url}"> {self.title} </a>'

class Dsensor(models.Model):
    time = models.CharField(primary_key=True,max_length=10)
    humi = models.FloatField()
    tem = models.FloatField()
    
    class Meta:
        db_table = "dsensor"



class User(models.Model):
    time = models.CharField(primary_key=True, max_length=10)
    user = models.CharField(max_length=10)

    class Meta:
        db_table = "user_data"

django-calendar1/cal/forms.py
from django.forms import ModelForm, DateInput
from cal.models import Event

class EventForm(ModelForm):
  class Meta:
    model = Event
    # datetime-local is a HTML5 input type, format to make date time show on fields
    widgets = {
      'start_time': DateInput(attrs={'type': 'datetime-local'}, format='%Y-%m-%dT%H:%M'),
      'end_time': DateInput(attrs={'type': 'datetime-local'}, format='%Y-%m-%dT%H:%M'),
    }
    fields = '__all__'

  def __init__(self, *args, **kwargs):
    super(EventForm, self).__init__(*args, **kwargs)
    # input_formats parses HTML5 datetime-local input to datetime field
    self.fields['start_time'].input_formats = ('%Y-%m-%dT%H:%M',)
    self.fields['end_time'].input_formats = ('%Y-%m-%dT%H:%M',)

django-calendar1/cal/views.py
from django.http import HttpResponse, JsonResponse, HttpResponseRedirect
from .models import Dsensor
from django.forms.models import model_to_dict
from django.views.decorators.clickjacking import xframe_options_exempt
import hashlib
from django.views import generic
from django.utils.safestring import mark_safe
from datetime import datetime, timedelta, date
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.utils.safestring import mark_safe
import calendar
from django.views.decorators.clickjacking import xframe_options_deny
from django.views.decorators.clickjacking import xframe_options_sameorigin
from .models import User
from django.views.decorators import gzip
from django.http import StreamingHttpResponse
import cv2
import threading
import face_recognition


from .models import *
from .utils import Calendar
from .forms import EventForm

def index(request):
    return HttpResponse('hello')

class CalendarView(generic.ListView):
    model = Event
    template_name = 'cal/calendar.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        d = get_date(self.request.GET.get('month', None))
        cal = Calendar(d.year, d.month)
        html_cal = cal.formatmonth(withyear=True)
        context['calendar'] = mark_safe(html_cal)
        context['prev_month'] = prev_month(d)
        context['next_month'] = next_month(d)
        return context

def get_date(req_month):
    if req_month:
        year, month = (int(x) for x in req_month.split('-'))
        return date(year, month, day=1)
    return datetime.today()

def prev_month(d):
    first = d.replace(day=1)
    prev_month = first - timedelta(days=1)
    month = 'month=' + str(prev_month.year) + '-' + str(prev_month.month)
    return month

def next_month(d):
    days_in_month = calendar.monthrange(d.year, d.month)[1]
    last = d.replace(day=days_in_month)
    next_month = last + timedelta(days=1)
    month = 'month=' + str(next_month.year) + '-' + str(next_month.month)
    return month

def event(request, event_id=None):
    instance = Event()
    if event_id:
        instance = get_object_or_404(Event, pk=event_id)
    else:
        instance = Event()

    form = EventForm(request.POST or None, instance=instance)
    if request.POST and form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('cal:calendar'))
    return render(request, 'cal/event.html', {'form': form})



def main(request):
    data = Dsensor.objects.all()
    data_list = [entry for entry in data]
    last_data=data_list[-12:]

    return render(request, 'main.html', {'last_data': last_data})


def login(request):
    user_data = User.objects.all()
    user_list = [entry for entry in user_data]
    last_user=user_list[-1] if user_data else None

    return render(request,'login.html', {'user_data':last_user})




def home(request):
    data = Dsensor.objects.all()
    data_list = [entry for entry in data]
    last_data=data_list[-12:]

    return render(request, 'home.html', {'last_data': last_data})

def cam(request):
    context={}
    
    return render(request, "cam.html",context)
    
def user(request):
    user_data = User.objects.all()
    user_list = [entry for entry in user_data]
    last_user=user_list[-1] if user_data else None

    return render(request, 'user.html', {'user_data':last_user})

@xframe_options_deny
def view_one(request):
    return HttpResponse("I won't display in any frame!")

@xframe_options_sameorigin
def view_two(request):
    return HttpResponse("Display in a frame if it's from the same origin as me.")

django-calendar1/cal/templates/cal/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
    crossorigin="anonymous">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css" integrity="sha384-+d0P83n9kaQMCwj8F4RJB66tzIwOKmrdb46+porD/OvrJ+37WqIM7UoBtwHO6Nlg"
    crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="{% static 'cal/css/styles.css' %}">
  <title>Django Calendar App</title>
</head>

<body>
  <h1 class="title">{% block title %}{% endblock %}</h1>
  <hr>
  {% block content %}
  {% endblock %}

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>

  {% block script %}
  {% endblock %}
</body>
</html>

django-calendar1/cal/templates/cal/calendar.html
{% extends 'cal/base.html' %}

{% block title %}

{% endblock %}

{% block content %}
<style>
.calendar {
  width: 100%;
  max-height: 100vh;
  overflow: hidden;
  font-size: 13px;
}

.calendar td {
  width: calc(100% / 7);
  height: calc(100vh / 6);
  padding: 20px 0px 0px 5px;
}
</style>

<div class="clearfix">
    <a class="btn btn-info left" href="{% url 'cal:calendar' %}?{{ prev_month }}"> Previous Month </a>
    <a class="btn btn-info right" href="{% url 'cal:calendar' %}?{{ next_month }}"> Next Month </a>
    <a class="btn btn-info right" href="{% url 'cal:event_new' %}"> New Event </a>
</div>

{{ calendar }}
{% endblock %}

django-calendar1/cal/templates/cal/event.html
{% extends 'cal/base.html' %}

{% block title %}
Event
{% endblock %}

{% block content %}
<div class="clearfix">
  <a class="btn btn-info left" href="{% url 'cal:calendar' %}"> Calendar </a>
</div>

{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                {{ field.label }} <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            {{ field.label }} <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}

<form method="post">
  {% csrf_token %}
  <table class="form form-table">
    {{ form }}
    <tr><td colspan="2"><button type="submit" class="btn btn-info right"> Submit </button></td></tr>
  </table>
</form>
{% endblock %}

django-calendar1/cal/templates/cam.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<h1> video </h1>

<table>
    <tr>
        <td width="50%">
            <img src="/mobile/detectme/" style="width:200px;" />
        </td>
    </tr>
</table>

</body>
</html>

django-calendar1/cal/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
  <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0" />
  <title>USER</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="shortcut icon" href="/static/icon.png">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  <style>
    /* Remove the navbar's default margin-bottom and rounded borders */ 
    @font-face {
      font-family: 'NeoDunggeunmo';
      src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_2001@1.3/NeoDunggeunmo.woff') format('woff');
    }
    .navbar-inverse .navbar-nav>.active>a, .navbar-inverse .navbar-nav>.active>a:focus, .navbar-inverse .navbar-nav>.active>a:hover {
      background-color: #e3dfdf;
    }

    .navbar {
      margin-bottom: 0;
      border-radius: 0;
      padding-top: 5px;
      padding-bottom: 5px;
      background-color: #e3dfdf;
      border-color: #e3dfdf;
    }
    
    .navbar-brand { 
      clear: left;
      padding-left: 25px;
      padding-bottom: 20px;
      height: auto;
    }

    .navbar-inverse .navbar-nav>li>a {
      color: #202135;
    }

    .nav>li>a{
      padding-top: 25px;
      font-size: 17px;
    }

    .hover-zoom:hover {
      animation: zoom-animation 0.6s infinite alternate;
    }

    @keyframes zoom-animation {
      0% {
        transform: scale(1);
      }
      100% {
        transform: scale(1.5);
      }
    }
    
    .hover-zoom2:hover {
      transform: scale(1.5);
      transition: transform 0.5s ease-in-out;
    }
  

  </style>
</head>
<body>
  <nav class="navbar navbar-inverse">

    <div class="container-fluid">
      <div class="navbar-header">
        <div class="Clock">
          <h3>
            <div id="Clockday">00 00 00</div><br>
            <div id="Clock">00:00</div>
          </h3>

          <script>
              function Clock() {
                  var date = new Date();
                  var YYYY = String(date.getFullYear());
                  var MM = String(date.getMonth() + 1);
                  var DD = Zero(date.getDate());
                  var hh = Zero(date.getHours());
                  var mm = Zero(date.getMinutes());
                  var ss = Zero(date.getSeconds());
                  var Week = Weekday();
                  Write(YYYY, MM, DD, hh, mm, ss, Week);
                  //시계에 1의자리수가 나올때 0을 넣어주는 함수 (ex : 1초 -> 01초)
           
                   function Zero(num) {
                       return (num < 10 ? '0' + num : '' + num);
                   }
           
                  //요일을 추가해주는 함수
                   function Weekday() {
                       var Week = ['토', '월', '화', '수', '목', '금', '토'];
                       var Weekday = date.getDay();
                       return Week[Weekday];
                   }
           
           
                  //시계부분을 써주는 함수
                   function Write(YYYY, MM, DD, hh, mm, ss, Week) {
                       var Clockday = document.getElementById("Clockday");
                       var Clock = document.getElementById("Clock");
       
                       Clock.innerText = hh + ':' + mm + ':' + ss;
                       Clockday.innerText = YYYY + '년 ' + MM + '월 ' + DD + '일 ' + Week;
                   }
               }
           
               setInterval(Clock, 1000); //1초(1000)마다 Clock함수를 재실행 한다
           </script>
       
       </div>
      </div>
      <div class="collapse navbar-collapse" id="myNavbar">
        <ul class="nav navbar-nav navbar-right">
        </ul> 
      </div>
    </div>
  </nav>

</script>

{% block content %}
{% endblock %}


</body>
</html>

django-calendar1/cal/templates/login.html
<!DOCTYPE HTML>
<html>
<head>
  <title>LOGIN</title>
  <style>
    * {
      margin: 0;
      padding: 0;
    }

    html, body {
      height: 100%;
      overflow: hidden;
      justify-content: center;
      align-items: center;
      margin:40px;
    }

    .wrapper {
      display: flex;
      flex-direction: column;
      height: 100%;
    }

    .top {
      flex: 7;
      display: flex;
      justify-content: center;
      align-items: center;

    }

    .bottom {
      flex: 3;
      display: flex;
      justify-content: center;
      align-items: center;
    }

    .main {
      width: 800px;
      height: 100%;
      display: flex;
      flex-direction: column;
      justify-content: center;
      align-items: center;
      border: 1px solid lightgrey;
      border-radius: 5px;
    }

    .box1 {
      flex-grow: 1;
      display: flex;
      justify-content: center;
      align-items: center;
      overflow: hidden;
    }

    .box1 iframe {
      width: 700px;
      height: 500px;
      overflow: hidden;
      border: none;
    }

    .logo {
      margin-top: 0;
      margin-bottom: 20px;
      text-align: center;
      margin-top: 20px;
    }

    #login {
      width: 100%;
      background-color: rgb(154, 167, 172);
      border-color: transparent;
      color: white;
      padding: 10px;
      text-decoration: none;
    }

    #alert {
      margin-top: 0;
      text-align: center;
    }

    #user-link {
      display: none;
    }
  </style>
</head>
<body>
  <div class="wrapper">
    <div class="top">
      <div class="main">
        <h1 class="logo">FACE ID</h1>
        <div class="container">
          <div class="box1">
            <iframe src="" frameborder="0"></iframe>
          </div>
        </div>
      </div>
    </div>
    <div class="bottom">
      <div style="text-align: center;">
        {% if user_data.user != 'Unknown' %}
        <a href="/user/" id="login" class="account">LOGIN</a>
        {% else %}
        <span id="login" class="account">LOGIN</span>
        {% endif %}
      </div>
    </div>
  </div>
  <script>
    document.getElementById('login').addEventListener('click', function() {
      var lastUser = '{{ user_data.user }}';  // 데이터베이스에서 가져온 사용자 정보

      if (lastUser === 'unknown') {
        return false;  // 링크 클릭 이벤트를 중단합니다.
      }
    });
  </script>
</body>
</html>

django-calendar1/cal/templates/main.html
<!DOCTYPE HTML>
<html>
<head>
    <meta http-equiv="refresh" content="5">
    <title>MAIN</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0" />
<style>
html, body {
  height: 100%;
  margin: 0;
  padding: 0;
}
#container {
  height: 100%;
  display: flex;
  flex-direction: column;
  padding-left : 30px;
}
#A {
flex: 30;
width: 100%;
display: flex;
justify-content: center;
align-items: center;
flex-direction: column;
text-align: center;
}

#B {
flex: 35;
width: 100%;
display: flex;
flex-direction: row;
}

#B1 {
flex: 70;
height: 70%;
padding: 10px; /* 여백 추가 */
}

#B2 {
    flex: 30;
    height: 100%;
    display: flex;
    justify-content: center;
    align-items: center;
}

#B2 i {
    font-size: 60px; /* 아이콘 크기 조정 */
}

#C {
flex: 35;
width: 100%;
display: flex;
flex-direction: row;
}

#C1 {
flex: 70;
height: 70%;
padding: 10px; /* 여백 추가 */
}

#C2 {
flex: 30;
height: 100%;
display: flex;
justify-content: center;
align-items: center;
}
#C2 i {
    font-size: 60px; /* 아이콘 크기 조정 */
}

.chart-container {
width: 100%;
height: 100%;
padding: 10px; /* 내부 여백 추가 */
}

.Clock {
display: flex;
flex-direction: column;
align-items: center;
justify-content: center;
font-size: 40px;
}

#Clockday,
#Clock,
#temperature,
#humidity {
font-family: "Arial", sans-serif;
}

.login-container {
  position: absolute;
  bottom: 10px;
  right: 10px;
}

.login-button {
  background-color: skyblue;
  color: white;
  padding: 10px 20px;
  border: none;
  border-radius: 5px;
  cursor: pointer;
}
</style>

<script src="https://canvasjs.com/assets/script/jquery-1.11.1.min.js"></script>
<script src="https://cdn.canvasjs.com/canvasjs.min.js"></script>
<script>
    window.onload = function () {
    
        var chart1 = new CanvasJS.Chart("chartContainer1", {            
            title:{
                text: ""              
            },
            axisY: {
                suffix: " °C",
                maximum: 40,
                gridThickness: 0
            },
    
            data: [{
                type: "splineArea", // splineArea 타입으로 변경
                fillOpacity: 0.1,
                color: "#F08080",
                indexLabelFormatter: formatter1,
                dataPoints: [
                    { label: "", y: {{ last_data.0.tem }} },
                    { label: "", y: {{ last_data.1.tem }} },
                    { label: "", y: {{ last_data.2.tem }}},
                    { label: "", y: {{ last_data.3.tem }}},
                    { label: "", y: {{ last_data.4.tem }} },
                    { label: "", y: {{ last_data.5.tem }} },
                    { label: "", y: {{ last_data.6.tem }}},
                    { label: "", y: {{ last_data.7.tem }} },
                    { label: "", y: {{ last_data.8.tem }} },
                    { label: "", y: {{ last_data.9.tem }} },
                    { label: "", y: {{ last_data.10.tem }} },
                    { label: "", y: {{ last_data.11.tem }} }
                ]
            }]
        });
    
        chart1.render();
    
        var chart2 = new CanvasJS.Chart("chartContainer2", {            
            title:{
                text: ""              
            },
            axisY: {
                suffix: " %",
                maximum: 80,
                minimum: 35,
                gridThickness: 0
            },
    
            data: [{
                type: "splineArea", // splineArea 타입으로 변경
                fillOpacity: 0.1,
                color: "#91AAB1",
                indexLabelFormatter: formatter2,
                dataPoints: [
                    {label: "", y: {{ last_data.0.humi }} },
                    { label: "", y: {{ last_data.1.humi }} },
                    { label: "", y: {{ last_data.2.humi }}},
                    { label: "", y: {{ last_data.3.humi }}},
                    { label: "", y: {{ last_data.4.humi }} },
                    { label: "", y: {{ last_data.5.humi }} },
                    { label: "", y: {{ last_data.6.humi }}},
                    { label: "", y: {{ last_data.7.humi }} },
                    { label: "", y: {{ last_data.8.humi }} },
                    { label: "", y: {{ last_data.9.humi }} },
                    { label: "", y: {{ last_data.10.humi }} },
                    { label: "", y: {{ last_data.11.humi }} }
                ]
            }]
        });
    
        chart2.render();
    
        function formatter1(e) { 
            return e.dataPoint.y + " °C";
        } 

        function formatter2(e) { 
            return e.dataPoint.y + " %";
        } 
    }
</script>
</head>
<body>
<div id="container">
  <div id="A">
    <div class="Clock">
        <div id="Clockday">00 00 00</div><br>
        <div id="Clock">00:00</div>
        <script>
            function Clock() {
                var date = new Date();
                var YYYY = String(date.getFullYear());
                var MM = String(date.getMonth() + 1);
                var DD = Zero(date.getDate());
                var hh = Zero(date.getHours());
                var mm = Zero(date.getMinutes());
                var ss = Zero(date.getSeconds());
                var Week = Weekday();
                Write(YYYY, MM, DD, hh, mm, ss, Week);
                //시계에 1의자리수가 나올때 0을 넣어주는 함수 (ex : 1초 -> 01초)
         
                 function Zero(num) {
                     return (num < 10 ? '0' + num : '' + num);
                 }
         
                //요일을 추가해주는 함수
                 function Weekday() {
                     var Week = ['토', '월', '화', '수', '목', '금', '토'];
                     var Weekday = date.getDay();
                     return Week[Weekday];
                 }
         
         
                //시계부분을 써주는 함수
                 function Write(YYYY, MM, DD, hh, mm, ss, Week) {
                     var Clockday = document.getElementById("Clockday");
                     var Clock = document.getElementById("Clock");
     
                     Clock.innerText = hh + ':' + mm + ':' + ss;
                     Clockday.innerText = YYYY + '년 ' + MM + '월 ' + DD + '일 ' + Week;
                 }
             }
         
             setInterval(Clock, 1000); //1초(1000)마다 Clock함수를 재실행 한다
         </script>
     
     </div>
     
    </div>
    <div id="B">
      <div id="B1">
        <div class="chart-container" id="chartContainer1"></div>
      </div>
      <div id="B2" style="display: flex; align-items: center;">
        <span id="temperature" style="font-size: 30px; display: flex; align-items: center;">
            <i class="material-icons" style="margin-right: 5px;">thermostat</i>
            {{ last_data.11.tem }} °C
        </span>
    </div>
    </div>
    <div id="C">
      <div id="C1">
        <div class="chart-container" id="chartContainer2"></div>
      </div>
      <div id="C2">
        <span class="material-symbols-outlined" style="font-size: 60px;">
            water_drop
            </span>
        <span id="humidity" style="font-size: 30px; display: flex; align-items: center;">
            <i class="material-icons" style="margin-right: 5px;"></i>
            {{ last_data.11.humi }} %
        </span>
      </div>
    </div>
</div>
<a href="/login/" class="account" style="position: absolute; top: 10px; right: 10px; border:none; outline: none; background: white; color: inherit; text-decoration: none;">FACE LOGIN</a>

</body>
</html>